FROM ls6-stud-registry.informatik.uni-wuerzburg.de/studwangsadirdja-project-nlp:0.0.1


WORKDIR /home/user
RUN pip3 install tqdm
# RUN pip3 install flair
# RUN pip3 install nltk
RUN pip3 install matplotlib
RUN pip3 install seaborn

# NAME=ls6-stud-registry.informatik.uni-wuerzburg.de/studwangsadirdja-project-nlp:0.0.2

