apiVersion: batch/v1
kind: Job
metadata:
  name: sim-cnn-9
  namespace: studheinickel
spec:
  template:
    spec:
      priorityClassName: research-med
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
                - matchExpressions:
                  - key: gputype
                    operator: In
                    values:
                      - rtx8000
                      - titan
                      - rtx2080ti
      containers:
        - name: text-cnn
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/studheinickel/sim-cnn:0.0.1
          imagePullPolicy: "Always"
          resources:
            limits:
              nvidia.com/gpu: "2"
              cpu: "10"
              memory: "32Gi"
          command: ["bash", "-c", "cd /home/stud/heinickel/scripts/text_cnn/ && python3 -u __main__.py"]
          volumeMounts:
            #- mountPath: /home/stud/heinickel/models # directory IN the container
            #  name: localdir-models # matches volume-name from below
            - mountPath: /home/stud/heinickel/logs # directory IN the container
              name: localdir-logs # matches volume-name from below
            #- mountPath: /home/stud/heinickel/data/embeddings # directory IN the container
            #  name: localdir-embeddings # matches volume-name from below
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: localdir-models
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studheinickel  # <username>
            path: "/home/stud/heinickel/mlnlp/models" # <full path to dir in CEPH>
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
        - name: localdir-logs
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studheinickel  # <username>
            path: "/home/stud/heinickel/mlnlp/logs" # <full path to dir in CEPH>
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
        - name: localdir-embeddings
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studheinickel  # <username>
            path: "/home/stud/heinickel/mlnlp/data/embeddings" # <full path to dir in CEPH>
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
